name: Test building pytket sphinx documentation

on:
  pull_request:
    branches:
      - main

jobs:
  check_changes:
    name: Check for changes to pytket or workflow
    runs-on: ubuntu-26.04
    outputs:
      pytket_or_workflow_changed: ${{ steps.filter.outputs.pytket_or_workflow }}
    steps:
    - uses: actions/checkout@v7
    - uses: dorny/paths-filter@v4.0.3
      id: filter
      with:
        base: ${{ github.ref }}
        filters: |
          pytket_or_workflow:
            - 'pytket/**'
            - '.github/workflows/build_pytket_docs.yml'

  build_pytket_and_test_sphinx_docs:
    name: Build and test pytket (ubuntu)
    needs: check_changes
    if: needs.check_changes.outputs.pytket_or_workflow_changed == 'true'
    runs-on: ubuntu-26.04
    steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
          enable-cache: true
          version: "0.10.9"
    - uses: actions/checkout@v7
      with: 
        submodules: true
    - uses: extractions/setup-just@v4
      with:
        just-version: 1.5.0
    - name: Select Python 3.12
      uses: actions/setup-python@v7
      with:
        python-version: '3.12'
    - name: Install conan
      uses: turtlebrowser/get-conan@v1.2
    - name: Set up conan
      run: |
        conan profile detect
        DEFAULT_PROFILE_PATH=`conan profile path default`
        PROFILE_PATH=./conan-profiles/ubuntu-26.04
        diff ${DEFAULT_PROFILE_PATH} ${PROFILE_PATH} || true
        cp ${PROFILE_PATH} ${DEFAULT_PROFILE_PATH}
        conan remote add tket-libs https://quantinuumsw.jfrog.io/artifactory/api/conan/tket1-libs --index 0
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: tket-dynamic-ubuntu-26.04
    - name: further ccache config
      run: |
        ccache --set-config base_dir=${HOME}
        ccache --set-config compiler_check=content
        ccache -p
    - name: Install tket
      run: conan create tket --user=tket --channel=stable --build=missing -o "boost/*":header_only=True -o "tklog/*":shared=True -o "tket/*":shared=True -tf ""
    - name: Set up Python (pull request)
      uses: actions/setup-python@v7
      with:
        python-version: '3.11'
    - name: Test building the Python Sphinx docs
      if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
      timeout-minutes: 20
      run: |
        cd pytket/docs
        just install-dev # Installs a develop wheel of pytket
        just build-strict
    - name: Upload artifact
      if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
      uses: actions/upload-artifact@v7
      with:
        name: pytket_docs
        path: pytket/docs/build/
