#!/bin/bash

# Copyright Quantinuum
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -evu

cd /tket

export PYBIN=/opt/python/cp312-cp312/bin
export PYEX=${PYBIN}/python
${PYEX} -m venv env
${PYEX} -m pip install conan
CONAN_CMD=${PYBIN}/conan
${CONAN_CMD} profile detect
DEFAULT_PROFILE_PATH=`${CONAN_CMD} profile path default`
PROFILE_PATH=./conan-profiles/${CONAN_PROFILE}
diff ${DEFAULT_PROFILE_PATH} ${PROFILE_PATH} || true
cp ${PROFILE_PATH} ${DEFAULT_PROFILE_PATH}
${CONAN_CMD} remote add tket-libs https://quantinuumsw.jfrog.io/artifactory/api/conan/tket1-libs --index 0

# Build tket and tket-c-api
${CONAN_CMD} create tket --user=tket --channel=stable -o boost/*:header_only=True
${CONAN_CMD} create tket-c-api -s build_type=Release --user=tket --channel=stable -o boost/*:header_only=True

# Upload to artifactory
${CONAN_CMD} remote login -p ${JFROG_ARTIFACTORY_TOKEN_3} tket-libs ${JFROG_ARTIFACTORY_USER_3}
${CONAN_CMD} upload tket/${TKET_VERSION}@tket/stable -r=tket-libs
${CONAN_CMD} upload tket-c-api/${TKET_VERSION}@tket/stable -r=tket-libs
